"""
FaceDetectionService — the reusable, high-level entry point for this
module.
"""

from __future__ import annotations

import logging
from pathlib import Path

import numpy as np

from app.ai.face_detection.interfaces import FaceDetectorBase, ImageLoaderBase
from app.ai.face_detection.models import DetectedFace


class FaceDetectionService:
    """
    Combines an ImageLoaderBase and a FaceDetectorBase into one simple,
    reusable service.

    "Reusable" here means specifically: construct ONE instance (which
    loads the underlying model exactly once, inside the injected
    detector's __init__) and call its methods repeatedly across an
    entire photo import batch — thousands of calls sharing the same
    loaded model, rather than paying model-load cost per photo.

    This class depends only on the two abstract interfaces (Dependency
    Inversion), so it never needs to change if SCRFD is swapped for a
    different detector, or OpenCV is swapped for a different image
    loader — a future caller just injects different concrete instances.
    """

    def __init__(
        self,
        detector: FaceDetectorBase,
        image_loader: ImageLoaderBase,
        logger: logging.Logger | None = None,
    ) -> None:
        """
        Args:
            detector: an already-constructed face detector (its model
                is already loaded by this point).
            image_loader: loads image files into arrays the detector
                can consume.
            logger: optional logger; defaults to "app.ai.face_detection".
        """
        self._detector = detector
        self._image_loader = image_loader
        self._logger = logger or logging.getLogger("app.ai.face_detection")

    def detect_in_file(self, path: Path) -> list[DetectedFace]:
        """
        Load an image from disk and detect faces in it.

        Args:
            path: path to an image file.

        Returns:
            A list of DetectedFace results (possibly empty — zero faces
            found is a normal, valid outcome, not an error).

        Raises:
            InvalidImageError: if the file can't be loaded/decoded.
            DetectionRuntimeError: if detection itself fails.
        """
        image = self._image_loader.load(path)
        faces = self._detector.detect(image)
        self._logger.info("Detected %d face(s) in %s", len(faces), path)
        return faces

    def detect_in_array(self, image: np.ndarray) -> list[DetectedFace]:
        """
        Detect faces in an already-loaded image array, skipping the
        file-loading step entirely.

        Useful when the caller already has image data in memory (e.g.
        a thumbnail already generated by another pipeline stage) and
        doesn't want to pay the cost of reading the file twice.

        Args:
            image: a BGR numpy array.

        Returns:
            A list of DetectedFace results.
        """
        faces = self._detector.detect(image)
        self._logger.info("Detected %d face(s) in provided image array", len(faces))
        return faces
