"""initial schema: photos, faces, persons

Revision ID: 629c0c092023
Revises: 
Create Date: 2026-07-18 20:23:46.978610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '629c0c092023'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('cover_face_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('perceptual_hash', sa.String(), nullable=True),
    sa.Column('taken_at', sa.DateTime(), nullable=True),
    sa.Column('camera_model', sa.String(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('orientation', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('import_batch_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_photos_file_hash'), ['file_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_photos_file_path'), ['file_path'], unique=True)
        batch_op.create_index(batch_op.f('ix_photos_import_batch_id'), ['import_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_photos_perceptual_hash'), ['perceptual_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_photos_taken_at'), ['taken_at'], unique=False)

    op.create_table('faces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('bbox_x', sa.Integer(), nullable=False),
    sa.Column('bbox_y', sa.Integer(), nullable=False),
    sa.Column('bbox_width', sa.Integer(), nullable=False),
    sa.Column('bbox_height', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faces_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_faces_photo_id'), ['photo_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faces_photo_id'))
        batch_op.drop_index(batch_op.f('ix_faces_person_id'))

    op.drop_table('faces')
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_photos_taken_at'))
        batch_op.drop_index(batch_op.f('ix_photos_perceptual_hash'))
        batch_op.drop_index(batch_op.f('ix_photos_import_batch_id'))
        batch_op.drop_index(batch_op.f('ix_photos_file_path'))
        batch_op.drop_index(batch_op.f('ix_photos_file_hash'))

    op.drop_table('photos')
    op.drop_table('persons')
    # ### end Alembic commands ###
